apiVersion: source.toolkit.fluxcd.io
kind: HelmRepository
metadata:
  name: test-helm-repository
  namespace: runtime
spec:
  interval: 2m
  secretRef:
    name: ${fluxHelmArtifactorySecret}
  timeout: 30s
  url: ${fluxHelmArtifactoryURL}
